added support for pam and nopam at the same time

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS ARG NEED_COMPAT_H build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OBJS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE CPP EGREP HAVE_GDBMDIR_NDBM_H LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS ARG NEED_COMPAT_H build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OBJS CHPASSOBJS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE CPP EGREP HAVE_GDBMDIR_NDBM_H LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1550,6 +1550,7 @@ NEED_COMPAT_H="COMPAT"
 
 
 
+
 PRESET_CFLAGS="$CFLAGS"
 
 OBJS="xstring.o ccgi.o configfile.o showmsg.o ephp.o accessdb.o createcookie.o searchdomain.o xmalloc.o out_of_memory.o run_cmd.o acl.o write_log.o cgipaf_func.o"
@@ -2755,6 +2756,8 @@ _ACEOF
 
    fi
 
+	CHPASSOBJS=$OBJS
+
  else
 	echo "$as_me:$LINENO: checking for pam_authenticate in -lpam" >&5
 echo $ECHO_N "checking for pam_authenticate in -lpam... $ECHO_C" >&6
@@ -2975,6 +2978,110 @@ echo "$as_me: error: no valid pam library found" >&2;}
    { (exit 1); exit 1; }; }
    	fi
    	OBJS="$OBJS passpam.o"
+	CHPASSOBJS="$OBJS pass.o salt.o"
+
+
+echo "$as_me:$LINENO: checking for crypt in -lcrypt" >&5
+echo $ECHO_N "checking for crypt in -lcrypt... $ECHO_C" >&6
+if test "${ac_cv_lib_crypt_crypt+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcrypt  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char crypt ();
+int
+main ()
+{
+crypt ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_crypt_crypt=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_crypt_crypt=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_crypt_crypt" >&5
+echo "${ECHO_T}$ac_cv_lib_crypt_crypt" >&6
+if test $ac_cv_lib_crypt_crypt = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCRYPT 1
+_ACEOF
+
+  LIBS="-lcrypt $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: no pam and no crypt library found i'm giving up" >&5
+echo "$as_me: error: no pam and no crypt library found i'm giving up" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+     	if test "$FREEBSDHOST" != "1"; then
+
+       		CHPASSOBJS="$CHPASSOBJS md5.o md5crypt.o"
+
+     	fi
+
+	if test "$BSDHOST" != "1"; then
+
+       		CHPASSOBJS="$CHPASSOBJS fgetpwnam.o";
+
+     	else
+
+       		{ echo "$as_me:$LINENO: WARNING: \"BSD host detected vmail password are disabled\"" >&5
+echo "$as_me: WARNING: \"BSD host detected vmail password are disabled\"" >&2;}
+
+     	fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define MD5_CRYPT 1
+_ACEOF
+
+
 fi
 
 if test "$with_libcrack" != "no"; then
@@ -12001,6 +12108,7 @@ s,@target_cpu@,$target_cpu,;t t
 s,@target_vendor@,$target_vendor,;t t
 s,@target_os@,$target_os,;t t
 s,@OBJS@,$OBJS,;t t
+s,@CHPASSOBJS@,$CHPASSOBJS,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
